package com.tward.watcher.core.model

import kotlinx.serialization.Serializable

/**
 * A single line of terminal output as captured by the desktop watcher.
 *
 * @property seq monotonically increasing sequence number within a session, used by
 *   clients to detect gaps after a reconnect.
 * @property timestamp epoch milliseconds at which the line was captured.
 */
@Serializable
data class TerminalLine(
    val seq: Long,
    val timestamp: Long,
    val stream: Stream,
    val text: String,
) {
    @Serializable
    enum class Stream {
        /** Standard output of the watched process. */
        STDOUT,

        /** Standard error of the watched process. */
        STDERR,

        /** Messages generated by terminal-watcher itself (process started, exited, ...). */
        SYSTEM,
    }
}
